package ArrayList.FriendList;

public interface iFriendList {
    //This method  will add a friend to your friendList...
      boolean acceptFriendRequest();
      //This method will remove a friend from your friendList...
      void removeFromFriendList();
      // This method will modify your profile if you wish to ...
      void modifyMyProfile();
      //This method will show you your complete FriendList...
      void viewFriendList();
      //This method will search a friend in your friendList by name and lets you view his profile...
      boolean findFriendInList();
}
